#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#include "include/svoBuilderDescriptorSet.glsl"

// equivalent to ceil(x / 64)
uint group_x_64(uint x) { return (x >> 6u) + (((x & 0x3fu) > 0u) ? 1u : 0u); }

void main() {
  uAllocBegin += uAllocNum;
  // uCounter stores accumulated tagged node count
  uAllocNum  = (uCounter << 3u) - uAllocBegin;
  uNumGroupX = group_x_64(uAllocNum);
}
