# It is not recommended to modify this file directly. 
# You should create CustomConfig.toml in the same directory and override the values there.

title = "default config"

[Application]
framesInFlight = 2

[ImguiManager]
fontSize = 20

[SvoBuilder]
# the voxel dimension within a chunk
chunkVoxelDim = 256
chunkDimX = 5
chunkDimY = 3
chunkDimZ = 5  

[SvoTracer]
aTrousSizeMax = 5
beamResolution = 8
taaSamplingOffsetSize = 64
lowResScale = 0.5

[SvoTracerTweakingData]
visualizeOctree = false
beamOptimization = true
traceSecondaryRay = true
taa = true
sunAngleA = 0.0
sunAngleB = 0.0
sunColorR = 1.0
sunColorG = 0.815
sunColorB = 0.678
sunLuminance = 1.0
sunSize = 0.5
temporalAlpha = 0.05
temporalPositionPhi = 0.99
aTrousIterationCount = 4
useVarianceGuidedFiltering = true
useGradientInDepth = true
phiC = 0.1
phiN = 20.0 
phiP = 0.05
phiZ = 0.6
changingLuminancePhi = true