# It is not recommended to modify this file directly. 
# You should create CustomConfig.toml in the same directory and override the values there.

title = "default config"

[Application]
framesInFlight = 2
isFramerateLimited = true

[Camera]
position = [0.0, 0.8, 0.0]
yaw = 270.0
pitch = 0.0
vFov = 60.0
movementSpeed = 0.2
movementSpeedBoost = 3.0
mouseSensitivity = 0.06

[ShadowMapCamera]
range = 1.0

[ImguiManager]
fontSize = 20

[SvoBuilder]
# the voxel dimension within a chunk
chunkVoxelDim = 256
chunkDim = [ 3, 1, 3 ]

[SvoTracer]
aTrousSizeMax = 5
beamResolution = 8
taaSamplingOffsetSize = 64
shadowMapResolution = 1024
upscaleRatio = 2.0

[SvoTracerTweakingData]
debugB1 = false
debugF1 = 0.0
debugI1 = 0
explosure = 10.0
visualizeChunks = false
visualizeOctree = false
beamOptimization = true
traceIndirectRay = true
taa = false
sunAltitude = 20.0
sunAzimuth = 0.0
rayleighScatteringBase = [ 5.802, 13.558, 33.1 ]
mieScatteringBase = 3.996
mieAbsorptionBase = 4.4
ozoneAbsorptionBase = [ 0.650, 1.881, 0.085 ]
sunLuminance = 2.0
atmosLuminance = 0.5
sunSize = 0.5
temporalAlpha = 0.01
temporalPositionPhi = 0.99
aTrousIterationCount = 3
phiC = 1.0
phiN = 20.0 
phiP = 0.05
minPhiZ = 0.35
maxPhiZ = 0.62
phiZStableSampleCount = 0.05
changingLuminancePhi = true
