# It is not recommended to modify this file directly. 
# You should create CustomConfig.toml in the same directory and override the values there.

title = "default config"

[Application]
framesInFlight = 2

[SvoBuilder]
# the voxel dimension within a chunk
chunkVoxelDim = 256
chunkDimX = 11
chunkDimY = 5
chunkDimZ = 11

[SvoTracer]
aTrousSize = 5
beamResolution = 8
taaSamplingOffsetSize = 64
lowResScale = 0.5

[SvoTracerTweakingData]
visualizeOctree = false
beamOptimization = true
traceSecondaryRay = true
taa = true
sunAngleA = 0.0
sunAngleB = 0.0
sunColor = [1.0, 0.815, 0.678]
sunLuminance = 1.0
sunSize = 0.5
temporalAlpha = 0.05
temporalPositionPhi = 0.99
atrousIterationCount = 3
useVarianceGuidedFiltering = true
useGradientInDepth = true
phiC = 0.01
phiN = 20.0
phiP = 0.01
phiZ = 0.8
ignoreLuminanceAtFirstIteration = true
changingLuminancePhi = true